on:
    # Trigger the workflow on push or pull request,
    # but only for the master branch
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
    # Also trigger on page_build, as well as release created events
    page_build:
jobs:
    docker:
        name: Docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.2
            - run: |
                    npm ci --only=production
                    docker build -t samthegitguy/bulletinboard -f Dockerfile . 
            - run: docker build -t samthegitguy/bulletinboard -f Dockerfile-lite .
  # You may pin to the exact commit or the version.
  # uses: EndBug/add-and-commit@a988073222b8bd50f3ecfca9c0ab7dfbf0d08ceb
            - uses: EndBug/add-and-commit@v4.4.0
                # Arguments for the git add command
                # The name of the user that will be displayed as the author of the commit
                # The email of the user that will be displayed as the author of the commit
                # The directory where your repository is located. You should use actions/checkout first to set it up
           
