name: Publish Docker image
on:
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download dependencies and build docker
        run: npm ci --only=production
  push_to_registry_lite:
    name: Push lite docker image to github packages
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v2
          
        - run: |
            cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u samthegitguy --password-stdin
            docker tag IMAGE_ID docker.pkg.github.com/samthegitguy/bulletinboard/IMAGE_NAME:VERSION
            docker push docker.pkg.github.com/samthegitguy/bulletinboard/IMAGE_NAME:VERSION
