on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: npm ci --only=production
      - name: Publish Image
        uses: craftech-io/package-action@v3.1.0
        with:
          tags: latest
          access_token: ${{ secrets.GITHUB_TOKEN }}
