name: Publish Docker image
on:
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download dependencies and build docker
        run: npm ci --only=production
  push_to_registry_lite:
    name: Push lite docker image to github packages
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - uses: docker/build-push-action
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: samthegitguy/bulletinboard/server
